### ISSUE TITLE
Provide hosted examples

### ISSUE THREAD

**Issue by beckyconning** [purescript-halogen/purescript-halogen#140]
Hosted examples allow potential users to try Halogen before they buy in by installing The Haskell Platform, PSC and related tools.

**Comment by jdegoes** [comment]
:+1:

**Comment by garyb** [comment]
@paf31 mentioned perhaps setting up a "Try Halogen" along the lines of "Try Thermite", "Try Flare", etc. which would satisfy this I think.

What's involved in making that happen Phil?

**Comment by paf31** [comment]
On the server side, I need a configuration file and a bunch of externs files from `psc` 0.8.0. The config file is a list of modules, one per line, topologically sorted in dependency order. Then I can set up the server side which will do the compilation. Here's an example:

https://github.com/purescript/trypurescript/pull/10

On the client side, you can copy the `gh-pages` branch from `trypurescript` into your own repo, and add the JavaScript build products you need, and the examples.

**Comment by garyb** [comment]
Ok thanks, once this release gets sorted out I'll try and put something together.

**Comment by soupi** [comment]
Update on what's needed to add a try-halogen backend for try-purescript:

- JS: add a backend option like [here](https://github.com/purescript/trypurescript/blob/gh-pages/js/index.js#L66)
- Html: add a halogen button like [here](https://github.com/purescript/trypurescript/blob/gh-pages/index.html#L60)
- Create a `bower.json`/`psc-package.json` file with all the dependencies you want to use for halogen and ask phil to spin a backend for it
- Write examples and link them in the main backend gist
- Ask phil to update the `core` main gist to link to the main halogen gist

**Comment by rintcius** [comment]
I'll have a look at this

**Comment by thomashoneyman** [comment]
Try PureScript now supports package set versions (it roughly tracks the latest package set), which includes Halogen. For example, as of today, you can paste this example into try.purescript.org to see a counter:

```purs
module Main where

import Prelude

import Data.Maybe (Maybe(..))
import Effect (Effect)
import Halogen as H
import Halogen.Aff as HA
import Halogen.HTML as HH
import Halogen.HTML.Events as HE
import Halogen.VDom.Driver (runUI)

main :: Effect Unit
main = HA.runHalogenAff do
  body <- HA.awaitBody
  runUI component unit body

data Action = Increment | Decrement

component =
  H.mkComponent
    { initialState
    , render
    , eval: H.mkEval $ H.defaultEval { handleAction = handleAction }
    }
  where
  initialState _ = 0
  
  render state =
    HH.div_
      [ HH.button [ HE.onClick \_ -> Just Decrement ] [ HH.text "-" ] 
      , HH.div_ [ HH.text $ show state ]
      , HH.button [ HE.onClick \_ -> Just Increment ] [ HH.text "+" ]
      ]
  
  handleAction = case _ of
    Increment -> H.modify_ \state -> state + 1
    Decrement -> H.modify_ \state -> state - 1
```
