### ISSUE TITLE
`Inject` style mechanism for choosing child slots implicitly

### ISSUE THREAD

**Issue by garyb** [purescript-halogen/purescript-halogen#478]
This might not jive with #439 though

**Comment by natefaubion** [comment]
`RowList` is equivalent to a `Coproduct`, so it would probably work fine. You would be selecting the first component that matches instead of directing it by the label. Not sure what the inferences issues would be like.

**Comment by natefaubion** [comment]
One problem with this though will be the compiler evidence. While the lookup is easy enough, it will inevitably require an `IsSymbol` constraint to dispatch when one is found. That means every time the function is called, it will have to pass in _all_ the `IsSymbol` constraints for the current component.

**Comment by natefaubion** [comment]
Oh, actually I take that back. The lookup doesn't require an IsSymbol constraint, only when it's found, so you should be able to do

```purescript
queryInj 
  :: forall s f g c m sym cs a
   . RowToList c cs
  => LookupQuery cs g sym
  => IsSymbol sym
  => g a
  => HalogenM s f c m (Maybe a)
```

Or something like that...

**Comment by garyb** [comment]
Closing this as I don't think it's that much better, and `Coproduct`s are log gone.
