### ISSUE TITLE
Benchmarks for recent Halogen versions

### ISSUE THREAD

**Issue by janat08** [purescript-halogen/purescript-halogen#632]
Therere bechmarka conducted against like very many libs, halogen 4 is amongst them, would it make sense to write halogen 5 case? https://stefankrause.net/js-frameworks-benchmark8/table.html

**Comment by natefaubion** [comment]
This particular benchmark essentially requires arbitrary vdom thunking, which halogen 5 supports. Halogen 5 still thunks at component boundaries, but you can insert calls to `memoized` or `lazy` anywhere now. I think the implementation of Halogen submitted for this benchmark only used a single monolithic component, so it was rendering the entire tree on every call. All the UI libraries perform poorly if you do this.

**Comment by janat08** [comment]
I was hoping that someone would submit a new benchmark. Maybe you could even add it into your CI.

**Comment by garyb** [comment]
Okay, I'll reopen this as something that might get looked at at some point, but it's not a high priority for me personally 🙂 

I don't think we'll be adding them to CI though, there seems to be quite a bit of variability in the performance there so I don't think it would tell us much useful.

**Comment by thomashoneyman** [comment]
I updated the Halogen benchmark to Halogen 5:
https://github.com/krausest/js-framework-benchmark/pull/716

It's not a huge change from previous Halogen versions, but it looks like the new benchmark reduces the slowdown from 2.3x -> 1.8x.

With this PR open I'm going to close this issue.

**Comment by thomashoneyman** [comment]
With the [current official benchmarks](https://krausest.github.io/js-framework-benchmark/current.html):

<img width="408" alt="Screen Shot 2020-04-06 at 11 08 04 AM" src="https://user-images.githubusercontent.com/10245104/78590685-0b64bc00-77f7-11ea-9aef-9c22cee578da.png">

**Comment by garyb** [comment]
Thanks @thomashoneyman!
