### ISSUE TITLE
Halogen Hooks?

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-halogen/purescript-halogen#639]
A while ago, I watched this keynote where they [announced React Hooks](https://www.youtube.com/watch?v=dpw9EHDh2bM) for the first time. I was wondering whether it would be desirable to implement something like that in Halogen or whether that should be a separate library or something. Thoughts? cc @thomashoneyman

**Comment by garyb** [comment]
Impeccable timing. He's been playing with some ideas around implementing hooks just these last few days :smile:. From the sneak peak I saw it could be a library too, it didn't need to mess with Halogen internals at all.

**Comment by thomashoneyman** [comment]
Yes, I've been working an an external library which implements hooks for Halogen. It's not quite the same as React Hooks given that the libraries don't work quite the same, but it has a similar feel. I expect to make the prototype public by the end of this month as I've only got snatches of time to work on it at the moment.

At this point you can recreate all the usual Halogen features with Halogen Hooks except for child components, which I haven't quite figured out yet.

As a quick example, this is the compiling hook version of the Halogen basic example:

```purs
component :: forall q i o m. H.Component HH.HTML q i o m
component = Hook.component \_ -> Hook.do
  state /\ setState <- Hook.useState \_ -> { enabled: false }

  let label = if state.enabled then "On" else "Off"

  Hook.pure do
    HH.button
      [ HP.title label 
      , HE.onClick \_ -> Just $ setState { enabled: not state.enabled } 
      ]
      [ HH.text label ]
```

versus the current example in this repository:

```purs
type State = { enabled :: Boolean }

data Action = Toggle

component :: forall q i o m. H.Component HH.HTML q i o m
component =
  H.mkComponent
    { initialState
    , render
    , eval: H.mkEval $ H.defaultEval { handleAction = handleAction }
    }

initialState :: forall i. i -> State
initialState _ = { enabled: false }

render :: forall m. State -> H.ComponentHTML Action () m
render state =
  let
    label = if state.enabled then "On" else "Off"
  in
    HH.button
      [ HP.title label
      , HE.onClick \_ -> Just Toggle
      ]
      [ HH.text label ]

handleAction ∷ forall o m. Action → H.HalogenM State Action () o m Unit
handleAction = case _ of
  Toggle ->
    H.modify_ \st -> st { enabled = not st.enabled }
```

And here's the Halogen basic effects example:

```purs
data Action = Regenerate 

component :: forall f i o. H.Component HH.HTML f i o Aff
component = Hook.component \input -> Hook.do
  state /\ runAction <- Hook.useAction handleAction \_ -> Nothing

  let value = maybe "No number generated yet" show state

  Hook.pure $ HH.div_
    [ HH.h1_ 
        [ HH.text "Random number" ]
    , HH.p_ 
        [ HH.text $ "Current value: " <> value ]
    , HH.button
        [ HE.onClick \_ -> Just $ runAction Regenerate ]
        [ HH.text "Generate new number" ]
    ]

handleAction :: Action -> H.HalogenM (Maybe Number) Action () Void Aff Unit
handleAction = case _ of
  Regenerate -> do
    newNumber <- H.liftEffect random
    H.put (Just newNumber)
```

[Here's a link to the regular Halogen version](https://github.com/purescript-halogen/purescript-halogen/blob/master/examples/effects-eff-random/src/Component.purs).

**Comment by thomashoneyman** [comment]
Halogen is already quite nice to use, but the place where a Hooks implementation will be especially nice is around reusing stateful logic. I hope that we can largely use hooks in place of renderless components like Select or where a renderless component would have been too large but you need to share state & behaviors, like a debouncer function.

**Comment by JordanMartinez** [comment]
> Impeccable timing. 

:smile: When you mentioned changing things in v6, I thought it was appropriate to bring up this topic due to not knowing whether a feature would need changing things in the internal. Thomas and I had talked about this idea briefly on Slack a while ago, so it seemed like a good time to bring it up.

@thomashoneyman Wow, that really makes a difference in the counter example.

**Comment by thomashoneyman** [comment]
Halogen Hooks is now a thing!
https://github.com/thomashoneyman/purescript-halogen-hooks
