### ISSUE TITLE
Question: Auto-focus newly created input field (Halogen 5)

### ISSUE THREAD

**Issue by chrisdone** [purescript-halogen/purescript-halogen#646]
Hi all,

Enjoying v5 of Halogen. I'm convinced it's the best-in-class for this kind of work. :muscle: 

Question: what's the established way when an action triggers a render that features a `<input type="text">` for the first time to make sure that the input is focused?

Use of the `autofocus` attribute works only once. And for a _second_ input, it doesn't have any effect.

I'm aware of e.g. `getHTMLElementRef`, so it's possible that I could trigger some kind of async `Effect`/`fork` to focus it based on an idle timer or something? 

An old technique works by an "Initializer" property of an element: https://stackoverflow.com/questions/32248943/automatically-focus-input-element-after-creation-in-purescript-halogen?rq=1 But I think this is at least two versions of Halogen old, and no longer applicable.

Any guidance? This of course a super standard thing in fat clients to need, so it's worth spelling out the latest way.

**Comment by natefaubion** [comment]
You can package up something with HTML.Core.ref.
https://github.com/purescript-halogen/purescript-halogen/blob/337d450fdd5e18de6f75920f808c34a173ff8d88/src/Halogen/HTML/Core.purs#L103-L106

The supported API in `HTML.Properties` packages it up as an internal `RefUpdate` input, which puts a reference in internal component state that you can pull out with a RefLabel, but you can have a version that just raises a user action.
https://github.com/purescript-halogen/purescript-halogen/blob/337d450fdd5e18de6f75920f808c34a173ff8d88/src/Halogen/HTML/Properties.purs#L133-L137
https://github.com/purescript-halogen/purescript-halogen/blob/7bb46c742c51b9cb32a6e798bf3e1336e4f3b463/src/Halogen/Query/Input.purs#L15-L17

I think this has been brought up before, but I can't find it atm.

**Comment by chrisdone** [comment]
Awesome! With that info, I was able to track down this:

**Comment by chrisdone** [comment]
I updated the issue title so that other intrepid Googlers can benefit.
