### ISSUE TITLE
Screen resets itself when state changes and page rerenders on mobile browser

### ISSUE THREAD

**Issue by srghma** [purescript-halogen/purescript-halogen#647]
https://giphy.com/gifs/bug-halogen-purescript-KAj4axQj1fDFTDXCKc

![Image of Yaktocat](https://media.giphy.com/media/KAj4axQj1fDFTDXCKc/giphy.gif)

image done on this branch https://github.com/srghma/purescript-ocelot/tree/halogen5-update and this commit https://github.com/srghma/purescript-ocelot/commit/8cee72016a98689188658464bfb160e9927e081d

halogen version 

  ▸  halogen-vdom/v6.1.0
  ▸  halogen/v5.0.0-rc.7

the issue is not present on:
- web chrome browser (with/without mobile view enabled, zoomed and not zoomed) 
- web firefox browser (with/without mobile view enabled, zoomed and not zoomed) 
- mobile firefox browser (zoomed and not zoomed)

but is present on mobile chrome browser (zoomed)

the same issue is present on halogen v4 https://citizennet.github.io/purescript-ocelot/

**Comment by garyb** [comment]
To be sure if this is a Halogen bug and not something to do with Ocelot or the particular page arrangement used on the docs site for it we'd probably want a much simpler reproducible case. Ideally a single component with one interactive element that triggers a state change.

**Comment by srghma** [comment]
yes, I wasn't been able to reproduce on https://github.com/srghma/purescript-halogen-material-components-web/commit/0aca867d0a2e62eb14fd2ada5d6b45f0dfca1f14

**Comment by garyb** [comment]
Does that mean we can close this issue then? 🙂
