### ISSUE TITLE
adding event handlers is super complex

### ISSUE THREAD

**Issue by shmish111** [purescript-halogen/purescript-halogen#650]
Halogen 5 made a big difference to usability however one thing I still struggle with is event handlers.

I wanted to subscribe to subscribe to events on an javascript element. In pure JS this would be pretty simple, probably something like:
```js
el.onSomeThingChanged(function(event) {
  someglobal.onDidChangeContent(event);
})
```
however in Halogen it was so difficult that I ended up doing part of it in JS behind the FFI, even with that I still ended up with something like:
```js
exports.onDidChangeContent_ = function (editor, handler) {
  editor.getModel().onDidChangeContent(function (event) {
    handler(event)();
  });
}
```
```haskell
      void $ H.subscribe (Emitter emitter) $ FFIModule.onDidChangeContent \_ -> do
          res <- some effects
          emitter $ Left $ HandleChange res
     pure mempty
```
which to me was very confusing. I think a big part of it is the documentation. Also in my case I don't need a finalizer and although the code looks ok with `pure mempty` this was difficult for me to work out. The docs for some of the individual pieces looks ok to me now that I've done it but it took me _a long_ time to work out what to do.

I don't have the brain power to suggest a better API at this time but I think there could be something nicer. Also some concrete examples in the documentation would help. I still don't really understand it all but it compiles and works so I'm happy :)

**Comment by garyb** [comment]
I assume this event isn't available in a form that you can use `addEventListener` on it? As if that were the case:

- and the element is in Halogen-rendered DOM you could use a `HE.handler` on the element directly
- if not an element in the Halogen DOM, you could use `eventListenerEventSource`

If neither of those are true, and it's only an "event" in the sense it's a callback based function, then what you wrote looks pretty straight forward to me. Although you are avoiding all the stuff that is provided to try and help make defining them easier: https://github.com/purescript-halogen/purescript-halogen/blob/v5.0.0-rc.9/src/Halogen/Query/EventSource.purs#L49-L111 :wink:.

See the Ace example for a similar usage to what you have, using some help: https://github.com/purescript-halogen/purescript-halogen/blob/v5.0.0-rc.9/examples/ace/src/AceComponent.purs#L59-L65

Halogen v6 is dropping coroutines for subscriptions in favour of `FRP.Event` which is simpler though.

- The corresponding Ace example: https://github.com/purescript-halogen/purescript-halogen/blob/next-6/examples/ace/src/AceComponent.purs#L59-L65
- Fewer helpers required... in fact, there's only one: https://github.com/purescript-halogen/purescript-halogen/blob/next-6/src/Halogen/Query/Event.purs

You can use `FRP.Event` in existing Halogen apps also, by making an `Event`-based-`EventSource`-helper and then just pushing messages into the `Event` part similar to that revised Ace example.

**Comment by shmish111** [comment]
Thanks, v6 looks interesting. On the one hand I feel very stupid as the more I look at this, the more obvious it becomes however on the other hand I think I'm a normal user so my inability to understand it without looking at it for quite a few hours from quite a few angles is pretty legit. I think it just needs super clear docs with examples, that's one area that makes Elm superior to PS.
