### ISSUE TITLE
Move ClassName to web-html

### ISSUE THREAD

**Issue by milesfrain** [purescript-halogen/purescript-halogen#656]
See https://github.com/purescript-web/purescript-web-html/issues/29

**Comment by thomashoneyman** [comment]
I think this should be done for the upcoming Halogen 6 version of the library, and that https://github.com/purescript-web/purescript-web-html/issues/29 ought to be merged. @garyb?

**Comment by thomashoneyman** [comment]
@milesfrain Any interest in taking this on now that https://github.com/purescript-web/purescript-web-html/pull/30 is merged?

**Comment by milesfrain** [comment]
Yep. Please assign to me
