### ISSUE TITLE
onFileUpload in Halogen 6

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-halogen/purescript-halogen#661]
In Halogen 5, `onFileUpload` was implemented like this:

https://github.com/purescript-halogen/purescript-halogen/blob/dd301747260620946956048a86e07e9efe1b6380/src/Halogen/HTML/Events.purs#L110-L117

In Halogen 6 there's no "maybe" action to raise, and instead an event always raises an action. So this function has been reimplemented like this:

```purs
onFileUpload
  :: forall r i t
   . Unfoldable t
  => (Maybe (t File) -> i)
  -> IProp (onChange :: Event | r) i
onFileUpload f =
  handler ET.change \ev ->
    f $ Event.target ev
      >>= HTMLInputElement.fromEventTarget
      >>= HTMLInputElement.files
      >>> unsafePerformEffect
      >>= items
      >>> pure
```

This behavior may not be correct; @garyb as the implementer of #636 and @BebeSparkelSparkel as the implementer of #623 do you have suggestions for changing this in the `next-6` branch?

**Comment by BebeSparkelSparkel** [comment]
Since `Unfoldable` is being used is the `Maybe` necessary?

**Comment by thomashoneyman** [comment]
It's used because the binds are all in `Maybe`. I could have this be `Maybe File -> i` instead, but there's not a way to say "any `t`".

**Comment by BebeSparkelSparkel** [comment]
It can be multiple files so it needs to be unfoldable

**Comment by BebeSparkelSparkel** [comment]
@thomashoneyman what commit are you working on?

**Comment by thomashoneyman** [comment]
This is on the `next-6` branch, which was rebased earlier today:
https://github.com/purescript-halogen/purescript-halogen/tree/next-6

**Comment by BebeSparkelSparkel** [comment]
I think this works well

```purescript
onFileUpload
  :: forall r i t
   . Unfoldable t
  => (t File -> i)
  -> IProp (onChange :: Event | r) i
onFileUpload f =
  handler ET.change \ev ->
    f $ fromMaybe none $ Event.target ev
      >>= HTMLInputElement.fromEventTarget
      >>= HTMLInputElement.files >>> unsafePerformEffect
      >>= items >>> pure
```

**Comment by thomashoneyman** [comment]
If @garyb is on board, that's fine with me!

**Comment by BebeSparkelSparkel** [comment]
@thomashoneyman thanks for helping with this
