### ISSUE TITLE
404 links for table of contents on docs 

### ISSUE THREAD

**Issue by chrissound** [purescript-halogen/purescript-halogen#673]
https://purescript-halogen.github.io/purescript-halogen/

Clicking the table of contents links shows a link like:
https://purescript-halogen.github.io/purescript-halogen/01-Rendering-Halogen-HTML.html (404)
while the clicking sidebar has a link of https://purescript-halogen.github.io/purescript-halogen/guide/01-Rendering-Halogen-HTML.html

**Comment by thomashoneyman** [comment]
This is fixed now that the documentation uses relative links and has a landing page for the documentation as a whole. Thanks!
