### ISSUE TITLE
Guide docs: Lifecycle and Subscriptions example code does not compile

### ISSUE THREAD

**Issue by and-pete** [purescript-halogen/purescript-halogen#678]
Hi all,

In the first full example in the guide's Lifecycles and Subscriptions page, there's the following `handleAction` function which does not compile:
```purs
handleAction :: forall o m. MonadEffect m => Action -> H.HalogenM State Action () o m Unit
handleAction = case _ of
  Initialize -> do
    handleAction Regenerate
    log ("Initialized: " <> show newNumber)  

  Regenerate -> do
    newNumber <- H.liftEffect random
    H.put (Just newNumber)

  Finalize -> ...
```
The handling of the `Initialize` constructor doesn't have a `newNumber` in scope for `log ("Initialized: " <> show newNumber)`.

As it's used as the first (I think?) example in the guide of a recursive effectful function, I figure you don't want another `newNumber <- H.liftEffect random` but instead something like:
```purs
handleAction = case _ of
  Initialize -> do
    handleAction Regenerate
    newNumber <- H.get
    log ("Initialized: " <> show newNumber)

    ...
```
As a side issue, for the example to be copy-pastable into TryPureScript like earlier examples, it'll also need the usual `main` function and its imports, which are currently absent.

Cheers :)

**Comment by thomashoneyman** [comment]
Thanks for finding this and describing the issue so well. This is fixed in https://github.com/purescript-halogen/purescript-halogen/commit/dd4337911c5b48b6d58d88020530748512e2a76e and all the examples in the chapter are runnable via Try PureScript now. Thanks again!
