### ISSUE TITLE
<picture> element support.  

### ISSUE THREAD

**Issue by shd101wyy** [purescript-halogen/purescript-halogen#681]
Hi there,

First of all. Thank you for the awesome library.  

I would like to use the `<picture>` element in my code to change some image sources based on the CSS `prefers-color-scheme`
https://stackoverflow.com/questions/55787167/how-to-change-image-source-based-on-css-prefers-color-scheme

But I don't see `HH.picture_` nor `HH.picture` available in Halogen.  
Do you have any suggestions for that? 

Thank you!

**Comment by MonoidMusician** [comment]
You can use [`Halogen.HTML.Elements.element`](https://github.com/purescript-halogen/purescript-halogen/blob/080e5254a0f981e2d41bd3e84ac24726fa29051a/src/Halogen/HTML/Elements.purs#L144-L151) to construct any node you want! Similarly you can use [`Halogen.HTML.Properties.prop` and `Halogen.HTML.Properties.attr`](https://github.com/purescript-halogen/purescript-halogen/blob/080e5254a0f981e2d41bd3e84ac24726fa29051a/src/Halogen/HTML/Properties.purs#L101-L118) to add custom properties/attributes. See those files for examples.

If you're doing custom properties/attributes, you won't need to mess around with the indexing system, but if you want to add a custom element with typechecked properties you can use the indices defined here: https://pursuit.purescript.org/packages/purescript-dom-indexed/7.0.0/docs/DOM.HTML.Indexed

(e.g. `Interactive ( srcset :: String )` for an element with a srcset property with a string value as well as other interactive properties.)

**Comment by shd101wyy** [comment]
@MonoidMusician Thank you for your answer! It works perfectly :)

**Comment by garyb** [comment]
This does seem like something worth adding in both places perhaps, since it is a standard HTML element now 🙂
