### ISSUE TITLE
Halogen.HTML.Properties missing style attribute

### ISSUE THREAD

**Issue by shmish111** [purescript-halogen/purescript-halogen#682]
I have a case where I need to add height to an element so I needed to add the property `style: "height: 55px"` however I had to manually add `attr (AttrName "style") "height: 55"` as it seems there is no `style` constructor even though there is a style property.

**Comment by garyb** [comment]
This was intentional: there's a typed `style` property provided by [purescript-halogen-css](https://github.com/purescript-halogen/). But yeah, that's maybe not a good enough reason to omit the `String` one.

**Comment by shmish111** [comment]
Oh, I'd never seen that library. It's a bit heavy handed for my use-case though.

**Comment by thomashoneyman** [comment]
Sorry, forgot to close this issue -- this was closed in #692 and #698.
