### ISSUE TITLE
documentation in Chinese

### ISSUE THREAD

**Issue by JacobChang** [purescript-halogen/purescript-halogen#696]
Recently I'm trying to learn about halogen and in the mean time, I start to translate the documentation to Chinese here 

https://github.com/JacobChang/purescript-halogen/tree/docs/zh-CN

should I submit an MR to contribute to this repo ? or I can keep it in my repo since not all documentation is finished yet.

**Comment by thomashoneyman** [comment]
I would love to support other languages for the Halogen documentation and I’m happy to hear you’re working on a translation. There are two things I’d like to figure out before we merge anything, but I’m open to having multiple languages included in this library.

1. How can we properly support multiple languages?
  There is a lot of documentation in this repo, from documentation comments to the written guides and miscellaneous README files. I don’t know how to handle something like source code internationalization, but I’m assuming you’re talking about the main guide here. For that we publish with mdBook, which afaik doesn’t have a good story for internationalization, so we might need to switch to something else to make this work. I would assume we could have subdirectories for each language which have the same content organized into the same pages, but in different languages.

2. Who will maintain translations?
  I don’t believe any of the Halogen maintainers are able to read or write Chinese, so we would need help maintaining a translation/translations as documentation changes over time. I’m reluctant to merge content into this repo without a dedicated person to maintain it.

I’d like to make sure we have a good handle on these two concerns before we merge anything in this repository.

That said: I am happy to link out to your repository as another option for those who would rather read the docs in Chinese. If you wanted to open an MR to update the main documentation README to state there’s also a Chinese version and link to it then I’m happy to merge that right away.

Thanks for bringing this up!

**Comment by JacobChang** [comment]
Maybe we can do the same thing as other JS frameworks, we can have separate repo for different languages, core team only need to maintain English version, let the community contribute other languges
https://github.com/vuejs
https://github.com/reactjs

Feels put all the documentation in the same repo will create too much burden for core team. Also, I think for most of user, translation for guide/tutorial is enough, no necessary to working on source generated documentation now.

Anyway, since I just started to translate the documentation, once I finished, I will submit an MR to add a link to my repo, no need to worry about this now.

**Comment by thomashoneyman** [comment]
I’m looking forward to that, and I agree it’s best that the core maintainers focus on the English version but make other translations visible. I’m also open to moving translations under the Halogen organization as well, as is done by Vue / React. Thanks for your work on this!
