### ISSUE TITLE
Update Halogen 6 for PureScript 0.14

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-halogen/purescript-halogen#719]
We plan to release Halogen 6 as the first 0.14-compatible version of this library because Halogen 6 is largely about quality of life improvements to the library without significant breaking changes. This issue tracks updating the Halogen 6 branch of the library for PureScript 0.14.

Currently blocked by:
  - [x] https://github.com/purescript-halogen/purescript-halogen-vdom/pull/45
  - [x] https://github.com/purescript-halogen/purescript-dom-indexed/pull/23

**Comment by JordanMartinez** [comment]
I approved the VDOM PR.

**Comment by JordanMartinez** [comment]
And just now approved the dom-indexed PR

**Comment by thomashoneyman** [comment]
Halogen 6 has now been released!
