### ISSUE TITLE
Type error at docs/guide/02-Introducing-Components.md

### ISSUE THREAD

**Issue by haishengwu-okta** [purescript-halogen/purescript-halogen#726]
1. At section `The H.Component Type`

Looks like it takes 5 parameters
`H.Component query input output m` shall be `H.Component html query input output m`
hence need to update the detail explanation

2. For the final code
- component type shall be `component :: forall query input output m. H.Component HH.HTML query input output m`
- on click function need to return `Maybe`

**Comment by haishengwu-okta** [comment]
nvm. I'm looking at doc at `master` branch which I guess is meant for V6. 🤦

**Comment by thomashoneyman** [comment]
@haishengwu-okta I was about to suggest that 😄 We aren’t too far away from the Halogen 6 release, fortunately.

**Comment by haishengwu-okta** [comment]
@thomashoneyman thanks! and very minor thing: at section `The H.Component Type`, when explaining `Component` type, the bullet number isn't perfect `2-5` which I think it shall be `1-4` ?

**Comment by thomashoneyman** [comment]
That _is_ an issue we should fix, probably by numbering all of them as 1. in the markdown.

**Comment by haishengwu-okta** [comment]
create #727

**Comment by thomashoneyman** [comment]
Thanks!
