### ISSUE TITLE
Doc: the examples of "performing effects" give TypesDoNotUnify Error

### ISSUE THREAD

**Issue by raptazure** [purescript-halogen/purescript-halogen#732]
The two examples [here](https://purescript-halogen.github.io/purescript-halogen/guide/03-Performing-Effects.html) give the following error:

![image](https://user-images.githubusercontent.com/44319278/110212169-0a3f8180-7ed5-11eb-805e-95c79c4feb7f.png)

**Comment by PureFunctor** [comment]
The examples were updated to Halogen 6, but https://try.purescript.org seems to be running at v0.13.x + Halogen 5 still, it seems.

**Comment by garyb** [comment]
Looks like you're using an example from `master` rather than a v5 branch - see also #726, #730, #731.
