### ISSUE TITLE
requestAll and tellAll functions

### ISSUE THREAD

**Issue by interzoneboy** [purescript-halogen/purescript-halogen#738]
Section 5 of the Halogen Guide references functions `requestAll` and `tellAll`, but these don't seem to exist. In the example code `H.requestAll` is used, with H the qualified Halogen module import, but this function is not located in that module (or any other module I've looked in).

**Comment by thomashoneyman** [comment]
Sorry about that, @interzoneboy -- looks like we forgot to include those in the module with `tell` and `request`. I've opened #739 to fix this in 6.1.0.

**Comment by interzoneboy** [comment]
Somehow it seems fun to me that the guide was *ahead* of things. That's not the usual problem! I'm just a midway competent haskell dabbler who needs some pretty web things and is just starting the learning... I love what I see so far in Purescript, and will help out wherever I can. Thanks for all the great work!
