### ISSUE TITLE
installation lacks a few libraries

### ISSUE THREAD

**Issue by KaneRoot** [purescript-halogen/purescript-halogen#756]
Here is what I had to install to compile halogen examples:

```sh
spago install arrays coroutines const
```

Should we add this line in `build-examples.sh`?

It created a few warnings, since not all of the examples needed them, but at least everything compiled.

**Comment by thomashoneyman** [comment]
We could add the dependencies to the individual `spago.dhall` files for the examples in question, if the error included which examples specifically are missing dependencies. Are you able to tell which examples are missing these?

**Comment by PureFunctor** [comment]
Just did a reproduction on this and found:
* `driver-routing`
  * \- aff-coroutines
  * \+ arrays
* `driver-websockets`
  * \+ arrays
  * \+ coroutines
* `lifecycle`
  * \+ arrays
  * \+ const
  
  I also have local changes for a PR, mind if I open one soon-ish?

**Comment by thomashoneyman** [comment]
Sure! Thanks.
