### ISSUE TITLE
Extra global information at render-time?

### ISSUE THREAD

**Issue by gardspirito** [purescript-halogen/purescript-halogen#781]
I have been working on a multilingual application, so I wanted to propagate translation data across the entire application. Translation data is accessed only at render time and does not affect behaviour of components in either way, but it turns out that in Halogen, as far I understand, it is impossible to pass extra data at render time (the type for render is just `state -> HTML (ComponentSlot slots m action) action`).

I think that this is a strange limitation.

**Comment by garyb** [comment]
What you're describing is exactly what I would call state information - unless in your case it's not possible to change the language once the app has been started?

If that's the case, then you can pass values down into the components and render functions like you would anywhere else:

``` purescript
component :: forall q i o m. Language -> H.Component q i o m
component lang =
  H.mkComponent
    { initialState: ...
    , render: render lang
    , eval: ...
    }

render :: forall m. Language -> State -> H.ComponentHTML Action Slots m
render lang state = ...
```

**Comment by gardspirito** [comment]
Thank you for your reply.

Well, in my case I would like to have ability to change language at runtime, but I don't like the idea of explicitly specifying "language" field on each and every component and explicitly handling language update considering the fact that it is generally the same for the entire system. I just feel like there is another, more flexible way.

Anyway, my problem is way too specific and maybe does not deserve attention. I guess I will survive through it with just multiple helper functions.

**Comment by garyb** [comment]
Have you taken a look at https://github.com/thomashoneyman/purescript-halogen-store?

**Comment by gardspirito** [comment]
Oh, I guess this looks interesting. Thank you.

**Comment by gardspirito** [comment]
Well, on my way to implementing helper functions I ended up with a problem that it's impossible to map state of `HalogenM state action slots output m` to a more generic one.

`imapState` does a good job for mapping, but inside of it happens unnecessary loss of information:
https://github.com/purescript-halogen/purescript-halogen/blob/5bcd961a4a3954f639da556ed6661b14bb425ae4/src/Halogen/Query/HalogenM.purs#L239
— applying `f'` in my case causes loss of information, which _could_ have been reattached with `f`, but it's impossible to because original state is lost.

Would it be hard to make a more generic version for `imapState` like 
```ps
wrapState :: forall state state' action slots output m
   . ((state -> state) -> state' -> state')
  -> HalogenM state action slots output m
  ~> HalogenM state' action slots output m
```
?

**Comment by MonoidMusician** [comment]
A similar change to `imapState` was requested before, in #645. Unfortunately progress stalled on it but maybe we can get it rolling again.
