### ISSUE TITLE
Export tellAll from Halogen.Query to Halogen

### ISSUE THREAD

**Issue by Swordlash** [purescript-halogen/purescript-halogen#798]
Sometimes I use `Halogen.Query.tellAll` to send messages to all children of some type, but I need to explicitly import `Halogen.Query` to do so. Is there any reason why it's not exported to `Halogen`?

**Comment by garyb** [comment]
#796 it'll be in the next release 🙂

**Comment by Swordlash** [comment]
Thanks, sorry, I didn't see such issue, perhaps because it's already solved :)
