### ISSUE TITLE
Question:  body-level events

### ISSUE THREAD

**Issue by Alch-Emi** [purescript-halogen/purescript-halogen#806]
Hello!

I'm a bit of a purescript/halogen newbie, and I just ran into a roadblock I was hoping I could get some help with.  I'm trying to detect a keypress of the arrow keys on a page being managed by Halogen.  I can add the onKeyDown event listener to my top-level div in halogen, but it seems like that alone isn't sufficient to detect keypresses.  From what I can tell, keyboard events are only fired if
- The user has some input element selected
- The event listener is registered to `<body>`

Unfortunately, I'm struggling to figure out how to add an event listener to the body using Halogen - I found a couple functions which I think I could use, but they require the event listener to be something along the lines of `KeyboardEvent -> Effect Unit` rather than `KeyboardEvent -> MyMessageType`.  I think I might be able to figure out how to pass the message to halogen from the outside, but this was starting to feel really messy for something which I would expect to be fairly common place, which is how I ended up here.

Any advice you might have is greatly appreciated!

Thanks!

**Comment by MonoidMusician** [comment]
Halogen has a mechanism for external subscriptions like that through the `subscribe` family of functions:
https://pursuit.purescript.org/packages/purescript-halogen/6.1.2/docs/Halogen.Query.HalogenM#v:subscribe

And there's a way to create an `Emitter` from a listener on an arbitrary node, taking a callback for actions in your component:
https://pursuit.purescript.org/packages/purescript-halogen/6.1.2/docs/Halogen.Query.Event#v:eventListener

You'll need to call the right `toEventTarget` to get an event target out of the body node once you look it up.

It looks like the keyboard input example in this repo uses these functions:
https://github.com/purescript-halogen/purescript-halogen/blob/master/examples/keyboard-input/src/Main.purs#L52-L56

Let us know if you need more pointers!

**Comment by Alch-Emi** [comment]
This is just what I was looking for!  Thank you so much!

**Comment by MonoidMusician** [comment]
Yay! Glad to hear :)
