### ISSUE TITLE
Doc: the examples of "An Aff Example: HTTP Requests" give TypesDoNotUnify Error on Halogen v7

### ISSUE THREAD

**Issue by SuperCipher** [purescript-halogen/purescript-halogen#812]
#### Relate issue
https://github.com/purescript-halogen/purescript-halogen/issues/732 (2 years ago)

Purescript version: https://github.com/purescript/package-sets/releases/download/psc-0.15.4-20220816/packages.dhall
Halogen version: v7.0.0
Spago version : 0.20.9
Operating system: MacOS 12.6.6

#### Step to reproduce
Following example document and run this [example](https://github.com/purescript-halogen/purescript-halogen/blame/v7.0.0/docs/guide/03-Performing-Effects.md#L153-L238) in Main.purs with `spago build`

#### Expect result
Compiled and run a website

#### Actual result
I got an error in the command line
```
Error found:
in module Main
at src/Main.purs:83:36 - 83:47 (line 83, column 36 - line 83, column 47)

  Could not match type

    ResponseFormat String

  with type

    AffjaxDriver


while checking that type ResponseFormat String
  is at least as general as type AffjaxDriver
while checking that expression string
  has type AffjaxDriver
in value declaration handleAction

See https://github.com/purescript/documentation/blob/master/errors/TypesDoNotUnify.md for more information,
or to contribute content related to this error.
```

#### Example code and setup repo
https://github.com/SuperCipher/purescript-halogen/tree/issue/example-types-do-not-unify-v7

**Comment by thomashoneyman** [comment]
This example needs to be updated now that Affjax has been split into Node and Web packages. You can see details about that in the affjax repository:
https://github.com/purescript-contrib/purescript-affjax
