### ISSUE TITLE
A bug? Weird behavior of text input fields.

### ISSUE THREAD

**Issue by thought2** [purescript-halogen/purescript-halogen#816]
From the following simple Halogen Component, I'd expect the input field to stay "x" after I typed "xa". (See update function below)

However, this is the behavior I am seeing:

![halogen-bug](https://github.com/purescript-halogen/purescript-halogen/assets/18749447/12afa349-7a4b-4af8-92c7-c8ec2347c29d)

The state changes to "x" as expected, but the input remains "xa".
I've tested this with a fresh parcel production build on Chrome and Firefox.
The code contains some similar transformations in the comments, which all work as expected.

Can someone reproduce this, or even have an explanation for this?

```hs
module Tmp.HalogenTry where

import Prelude

import Effect (Effect)
import Effect.Aff (Aff)
import Halogen (modify_)
import Halogen as H
import Halogen as Halogen
import Halogen.Aff (awaitBody, runHalogenAff)
import Halogen.HTML as HH
import Halogen.HTML.Events as HE
import Halogen.HTML.Properties as HA
import Halogen.VDom.Driver (runUI)
import Unsafe.Coerce (unsafeCoerce)

type Msg = String

component
  :: forall q i o
   . Halogen.Component q i o Aff
component =
  H.mkComponent
    { initialState
    , render
    , eval: H.mkEval $ H.defaultEval
        { handleAction = handleAction
        }
    }

  where
  initialState :: i -> String
  initialState _ = ""

  render state =
    HH.div []
      [ HH.input
          [ HA.type_ HA.InputText
          , HE.onInput (\event -> (unsafeCoerce event).target.value)
          , HA.value state
          ]
      , HH.text $ "state: " <> state
      ]

  handleAction (msg :: String) = do
    modify_ $ const (if msg == "xa" then "x" else msg)

    -- Those work as expected:
    --modify_ $ const (if msg == "xa" then "y" else msg)
    --modify_ $ const (if msg == "ax" then "x" else msg)
    --modify_ $ const (if msg == "abc" then "xyz" else msg)

    pure unit

main :: Effect Unit
main = runHalogenAff do
  body <- awaitBody
  runUI component unit body
```

**Comment by thomashoneyman** [comment]
You're setting the state to its same value (the value was "x", then you type "xa" and set the state to "x"), so no re-render is happening and the input field is diverging from your state. You'll see the behavior you expect so long as your state is changing. To force a state update even if you're setting the text to its same value, you could add an additional field to your state like this:

```
type State = { value :: String, force :: Int }
```

and if you are setting your new state to the same value as is present in the old state, you can also increment `force`. This will guarantee a state update and re-render.

**Comment by thought2** [comment]
I tried this, here's my modified code:

```hs
  (...)
  
  initialState :: i -> _
  initialState _ = { str: "", num: 0 }

  render state =
    HH.div []
      [ HH.input
          [ HA.type_ HA.InputText
          , HE.onInput (\event -> (unsafeCoerce event).target.value)
          , HA.value state.str
          ]
      , HH.text $ "state: " <> (show state)
      ]

  handleAction (msg :: String) = do
    modify_ $ \state -> { str: if msg == "xa" then "x" else msg, num: state.num + 1 }
```

I am still seeing the same behavior:
![halogen-bug2](https://github.com/purescript-halogen/purescript-halogen/assets/18749447/5caf7695-9c67-413b-aed8-fa393c0fbbe8)

**Comment by garyb** [comment]
Does it work if you use `HE.onValueChange`? I think what's happening is the value is being captured in the event cycle too soon, so you'd have to `preventDefault` the event.

Both `onValueChange` and `onValueInput` give you the new value rather than the `Event` also, saving that questionable `unsafeCoerce`.

I do have one other thought on this though... don't do it :smile:. From a UX perspective preventing input is bad, it's better to allow any input and show a validation message about why it's disallowed instead.

**Comment by thought2** [comment]
@garyb Agree, UX wise it's not a good idea. Already dropped that idea in my real use case. So no urgency :)
However I thought it's worth mentioning here, because it might be a bug: I checked the example in React and Elm and both work according to my expectation.

In Halogen I tried `onValueInput` but the behavior is the same. `onValueChange` works after the first enter hit but not after the second.
