### ISSUE TITLE
Child component is destroyed while parent component handles output from that child

### ISSUE THREAD

**Issue by yaitskov** [purescript-halogen/purescript-halogen#818]
Hi,

I had a component with child one. Child component delegates REST integration to parent one.
The parent component  rendering:

```
  s <- get
  if s.isLoading 
    then H.text "loading"
    else H.slot _proxy unit component args ChildOutput
``` 

```
parentHandleAction = 
   case _ of 
     ChildOutput MakeFoo -> 
       H.tell _proxy unit PrintState
       H.modify_ _ { isLoading = true }
       -- do rest
       H.modify_ _ { isLoading = false }
       H.tell _proxy unit PrintState
```
Second `PrintState` query is delivered to the new child component.

This semantic was not obvious. 
I would expect a delay for GC child component until all transitive actions/queries originating from the time before when that component was alive are finished.

**Comment by garyb** [comment]
If I understand what you're saying correctly, I think you have a much more complicated idea of what is/should be happening than what Halogen does.

When the state changes, the component re-renders - it's as simple as that. When you query a child component, it goes to whatever is currently rendered. Even if you didn't `<do rest>` between the two `isLoading` toggles it would still be sending the second `PrintState` to a different component.

The semantics are intentionally kept as simple as possible, as in the past when we tried to do render batching stuff automatically we ended up having to force re-renders and think about things that we don't want to care about. Having the current state always reflect "reality" seems like most obvious thing to me?

But I may have misunderstood what you're getting at, when I saw the code at first I assumed it was probably going to be something weird happening related to the bug #657.

**Comment by yaitskov** [comment]
Thanks for the link. 
Halogen operates by terms such child and parent.
I think this is why I assumed some scoping. 

Child component state is lost, while parent serves a request from the child, because DOOM  reference to the child component for a moment disappears.  
Is there better workaround for this case than CSS display hack?:

```
render r htmlsWithStateFullSlots =
   H.div_
    [ H.div
        [ H.style $
            if r.isLoading
              then "display: none"
              else ""
        ]
        [ htmlsWithStateFullSlots ]
    , if r.isLoading
        then loadingDiv
        else H.text ""
    ]
```

I image a following low level API function to prevent GC until parent component is going to face GC itself:

```
gcChildWithMeOnly ::  slot -> HalogenM state action slots output m Unit
```

**Comment by yaitskov** [comment]
> I wouldn't really call it a hack, 

It is. CSS display is not composable - abstraction introduced via component hierarchy leaks in this case.

**Comment by garyb** [comment]
I'm going to close this as it's not something we're likely to change any time soon.

If we were to do something about this in the future I'd be more inclined to have something where you can initialize a component outside of `render` and store it in the component state, and then use that when you want something that will preserve its state when it's not present in the render tree. Basically introduce it as an alternative to referential identity for child components.

It might actually be possible to hack something in for that just now, essentially launching the resident component in an entirely separate context (using `runHalogenAff`, etc. like at the top level) and then attaching it to an element with a `Ref` or something.
